### ISSUE TITLE
user->identity

### ISSUE THREAD

**Issue by CyanoFresh** [bazilio91/yii2-stubs-generator#7]
Hello. Yii2 has identity class in user class. Plugin doesn't generate code for it

**Comment by bazilio91** [comment]
Plugin has no idea about components if u dont mention em in config. If u want that autocomplete - define user component or teach our plugin to read runtime. ж)

**Comment by CyanoFresh** [comment]
but I have this in config:
```
        'user' => [
            'identityClass' => 'app\models\User',
            'enableAutoLogin' => true,
        ],
```

**Comment by bazilio91** [comment]
Done in https://github.com/bazilio91/yii2-stubs-generator/commit/53e499dc1ac404b9ac1b1c99dfcf919623a12661
